name: reminder_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  provider: ^6.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Helvetica
      fonts:
        - asset: fonts/Helvetica.ttf
    - family: Helvetica-Bold
      fonts:
        - asset: fonts/Helvetica-Bold.ttf
